title: More Equal Animals
name: Daniel Larimer
user_description: Programmer, Entrepreneur, Philosopher
profile_pic: /assets/img/dlcaricature.jpg
favicon: /assets/img/favicon.png
copyright_name: Daniel Larimer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://moreequalanimals.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-seo-tag

markdown: kramdown

twitter:
  username: bytemaster7

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

disqus:
  shortname: moreequalanimals 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
